# -*- coding: utf-8 -*-
"""text_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15z-0Ofx9Ge20vP8Pdq5QxWrSvv60cfmJ
"""

def text_to_csv(file_path, output_path, output_name):
  '''
    file_path:  The path to the txt file that is meant to be converted to csv(text file to be extracted.)
    output_path: Output folder for your CSV
    output_name: The name to save the csv file (no need to add the .csv file extension to it)
  '''
  try:
    text_content = open(file_path , "r")
    text_string = text_content.read().replace("\n", " ")
    text_content.close()
    characters_to_remove = [";","'s", "@", "&", 
      "(",")","!","+","_",":", '"',"'"]

    for item in characters_to_remove:
      text_string = text_string.replace(item,"")
      characters_to_replace = ["?"]

    for item in characters_to_replace:
      text_string = text_string.replace(item,".")
      sentences = text_string.split(".")

    j = 0
    for sentence in sentences:
      if len(sentence.lstrip()) <= 1:
        continue
      elif sentence[0] == " ":
        sentence = sentence[1:]
        sentences[j] = sentence.lower() + '.'
        j += 1
      else:
        sentences[j] = sentence.lower() + '.'
        j += 1
    sentences = sentences[0:j]

    df = pd.DataFrame(sentences,columns=['text'])
    try:
      destination = os.path.join(output_path, output_name) + '.csv'
      print(destination)
      df.to_csv(destination, index=False)
    except FileNotFoundError as fnfe:
      print('Check the output_path: ', fnfe)

  except FileNotFoundError as fnfe:
    print('Check the file_path: ',fnfe)


'''
How to use the script
file_path = '/content/drive/MyDrive/Omdena/fb62e200-0fa3-11ec-82a8-0242ac130003 (2).txt'
output_path = '/content/drive/MyDrive/Omdena/'
output_name = 'accoin_finished'
text_to_csv(file_path, output_path, output_name)
'''